# Generated by Django 5.1.1 on 2025-07-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_profile_image_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Image URL'),
        ),
    ]
